### ISSUE TITLE
Connecting to hipchat spams logs with TypeError: Object #<EnterMessage> has no method 'match'

### ISSUE THREAD

**Issue by SarahKowalik** [hassaku/hubot-suggest#4]
When starting up Hubot and connecting to HipChat with this plugin, the following is shown repeatedly in the logs (when connecting to channels, I think):

```
[Wed Feb 04 2015 15:58:07 GMT+1100 (AEDT)] ERROR TypeError: Object #<EnterMessage> has no method 'match'
  at /Users/sarah/src/hubot-lore/scripts/suggest.coffee:66:83, <js>:71:19
  at Listener.callback (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:184:52, <js>:131:16)
  at Listener.call (/Users/sarah/src/hubot-lore/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:197:9, <js>:142:33)
  at Robot.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:204:7, <js>:153:21)
  at HipChat.Adapter.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at /Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/src/hipchat.js:245:26
  at invokeCallback (/Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:161:15)
  at Object.<anonymous> (/Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:193:9)
  at /Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:13:16
  at process._tickCallback (node.js:419:13)

[Wed Feb 04 2015 15:58:07 GMT+1100 (AEDT)] ERROR TypeError: Object #<EnterMessage> has no method 'match'
  at /Users/sarah/src/hubot-lore/scripts/suggest.coffee:66:83, <js>:71:19
  at Listener.callback (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:184:52, <js>:131:16)
  at Listener.call (/Users/sarah/src/hubot-lore/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:197:9, <js>:142:33)
  at Robot.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:204:7, <js>:153:21)
  at HipChat.Adapter.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at /Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/src/hipchat.js:245:26
  at invokeCallback (/Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:161:15)
  at Object.<anonymous> (/Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:193:9)
  at /Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:13:16
  at process._tickCallback (node.js:419:13)

[Wed Feb 04 2015 15:58:07 GMT+1100 (AEDT)] ERROR TypeError: Object #<EnterMessage> has no method 'match'
  at /Users/sarah/src/hubot-lore/scripts/suggest.coffee:66:83, <js>:71:19
  at Listener.callback (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:184:52, <js>:131:16)
  at Listener.call (/Users/sarah/src/hubot-lore/node_modules/hubot/src/listener.coffee:27:7, <js>:23:14)
  at Robot.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:197:9, <js>:142:33)
  at Robot.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/robot.coffee:204:7, <js>:153:21)
  at HipChat.Adapter.receive (/Users/sarah/src/hubot-lore/node_modules/hubot/src/adapter.coffee:66:5, <js>:47:25)
  at /Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/src/hipchat.js:245:26
  at invokeCallback (/Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:161:15)
  at Object.<anonymous> (/Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:193:9)
  at /Users/sarah/src/hubot-lore/node_modules/hubot-hipchat/node_modules/rsvp/node/rsvp.js:13:16
  at process._tickCallback (node.js:419:13)
```

**Comment by hassaku** [comment]
This is the same with #2. So I close at this time.
Thank very much for your feedback 😃 .
